---
- name: "Instalacion y configuracion de serivdor Web"
  hosts: 192.168.0.14
  tasks:
    - name: "Descripcion del ejercicio"
      debug:
        msg: >
          En este ejericicio practicaremos el desarrollo de un playbook desde 0
          para ello, realizaremos varias tareas para levantar un servidor apache

    - name: "Instalacion de httpd"
      yum:
        name: [httpd, httpd-tools]
        state: latest
    
    - name: "Habilitar el firewalld"
      firewalld:
        service: [http, https]
        permanent: yes
        immediate: yes
        state: enabled
    
    - name: "Iniciamos el servicio httpd (tambien con el arranque del servidor)"
      service:
        name: httpd
        enabled: yes
        state: restart
    
    - name: "Deshabilitar el selinux"
      selinux:
        state: disabled
    
    - name: "Creacion del directorio para el Host Virtual"
      file:
        path: [/var/www/example.com/html, /var/www/example.com/log]
        owner: root
        group: root
        mode: 0765
        recurse: yes
        state: directory

    - name: "Modificar permisos del directorio"
      file:
        path: /var/www
        mode: 0755
        recurse: yes
        state: directory

    - name: "Creacion del index.html"
      file:
        path: /var/www/example.com/html/index.html
        owner: root
        group: root
        mode: 0755
        state: file
    
    - name: "Insercion de contenido en el index.html"
      blockinfile:
        path: /var/www/example.com/html/index.html
        block: |
          <html>
				      <head>
					      <title>Welcome to Example.com!</title>
				      </head>
				      <body>
					      <h1>Success! The example.com virtual host is working!</h1>
				      </body>
			    </html>
    
    - name: "Creacion del directorio sites"
      file:
        path: [/etc/httpd/sites-available, /etc/httpd/sites-enabled]
        owner: root
        group: root
        mode: 0765
        recurse: yes
        state: directory
    
    - name: "Insertar linea de configuracion"
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: "IncludeOptional sites-enabled/*.conf"
        create: yes
    
    - name: "Crear el fichero de configuracion para el Host Virtual"
      file:
        path: /etc/httpd/sites-available/example.com.conf
        owner: root
        group: root
        mode: 0755
        state: file
    
    - name: "Insercion de contenido en el index.html"
      blockinfile:
        path: /var/www/example.com/html/index.html
        block: |
          <VirtualHost *:80>
            ServerName www.example.com
            ServerAlias example.com
            DocumentRoot /var/www/example.com/html
            ErrorLog /var/www/example.com/log/error.log
            CustomLog /var/www/example.com/log/requests.log combined
          </VirtualHost>
    
    - name: Create a symbolic link
      file:
        src: /etc/httpd/sites-available/example.com.conf
        dest: /etc/httpd/sites-enabled/example.com.conf
        owner: root
        group: root
        state: link
    
    - name: "Reinicio del server"
      reboot: